import { demoProject, createSession, transition, viewSession, exportHandoff } from './engine.js';

const root = document.querySelector('#app');
let state = createSession(demoProject());
let lang = new URL(location.href).searchParams.get('lang') === 'en' ? 'en' : 'uk';
let selected = 'person-olena', filter = 'all', search = '', scenario = 'standard', touring = false, showExport = false;
let noticeTimer;
let imported = false;
const e = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t = (uk, en) => lang === 'uk' ? uk : en;
const l = value => typeof value === 'string' ? value : (value?.[lang] || value?.uk || '');
const arrow = '<svg width="14" height="14" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M4 10h11m-4-4 4 4-4 4" stroke="currentColor" stroke-width="1.5"/></svg>';
const download = '<svg width="14" height="14" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M10 3v9m-3-3 3 3 3-3M4 13v4h12v-4" stroke="currentColor" stroke-width="1.5"/></svg>';
const repo = 'https://github.com/DiadkoShmek/talent-research-workflow-prototype';
function statusLabel(status) { return {blocked:t('Конфлікт особи','Identity conflict'),'needs-review':t('Потрібна перевірка','Review needed'),ready:t('Готово до схвалення','Ready for approval'),approved:t('Передачу схвалено','Handoff approved')}[status]; }
function notify(message) {const node=document.querySelector('#notice');node.textContent=message;node.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>node.classList.remove('show'),6500);}
function act(action) {try {state=transition(state,action);render();return true;}catch(error){notify(t('Дію зупинено: ','Action stopped: ')+error.message);return false;}}
function reviewer(){return t('Учасник демонстрації','Demo participant');}
function metric(number,label,emphasis=''){return `<div class="metric ${emphasis}"><strong>${number.toString().padStart(2,'0')}</strong><span>${label}</span></div>`;}
function eventText(event,v){
 const name=v.candidates.find(c=>c.personKey===event.personKey)?.name || event.personKey;
 if(event.type==='review')return `${e(name)} · ${event.decision==='accept'?t('доказ прийнято','evidence accepted'):t('доказ відхилено','evidence rejected')} <span class="mono">${e(event.evidenceId)}</span>`;
 if(event.type==='identity')return `${e(name)} · ${event.confirmed?t('зв’язок записів підтверджено','record identity confirmed'):t('підтвердження особи знято','identity confirmation removed')}`;
 if(event.type==='approve')return `${e(name)} · ${t('дослідження схвалено до передачі','research handoff approved')}`;
 if(event.type==='revoke')return `${e(name)} · ${t('схвалення відкликано','approval revoked')}`;
 if(event.type==='setCutoff')return `${t('Змінено дату — усі перевірки та схвалення скасовано','Cutoff changed — all reviews and approvals invalidated')} (${e(event.cutoff)})`;
 return e(event.type);
}
function evidenceCard(ev,v){
 const criterion=v.project.criteria.find(c=>c.id===ev.criterionId);
 const h=v.project.hypotheses.find(h=>h.id===ev.hypothesisId);
 const reviewed=ev.review;
 return `<article class="evidence ${reviewed?.decision==='accept'?'accepted':reviewed?'rejected':''}" data-evidence="${e(ev.id)}">
 <div class="evidence-top"><strong>${e(l(criterion.label))}</strong><span class="badge ${!ev.fresh?'bad':reviewed?.decision==='accept'?'good':''}">${!ev.fresh?t('Застаріле спостереження','Old observation'):reviewed?reviewed.decision==='accept'?t('Прийнято людиною','Accepted by reviewer'):t('Відхилено','Rejected'):t('Не перевірено','Unreviewed')}</span></div>
 <blockquote>“${e(l(ev.quote))}”</blockquote>
 <div class="evidence-meta"><span>${e(l(h.label))}</span><span>·</span><time>${e(ev.source.observedAt)}</time></div>
 <details data-source="${e(ev.id)}"><summary>${t('Відкрити джерело й перевірити','Read source & review')}</summary>
 <div class="source-content"><span class="source-ref">${e(ev.source.ref)} · ${imported?t('імпортований документ','imported document'):t('вигаданий документ','fictional document')}</span>${e(l(ev.source.text))}</div>
 <p class="hint">${t('Наявність цитати не доводить відповідність критерію. Перевірте зміст. Це демонстраційний документ; його справжність не перевіряється.','A matching quote does not prove the criterion. Check its meaning. This is a demonstration document; its authenticity is not verified.')}</p>
 <form class="review-form" data-review-form="${e(ev.id)}"><label for="reason-${e(ev.id)}">${t('Ваш висновок — чому приймаєте або відхиляєте?','Your reason — why accept or reject?')}</label><input id="reason-${e(ev.id)}" name="reason" maxlength="500" required value="${e(reviewed?.reason||'')}" placeholder="${t('Що саме підтверджує цей уривок…','What this passage actually supports…')}"><div class="review-actions"><button class="button" name="decision" value="accept" type="submit" ${!ev.fresh?'disabled':''}>${t('Доказ підтверджує критерій','Evidence supports criterion')}</button><button class="button danger" name="decision" value="reject" type="submit">${t('Відхилити доказ','Reject evidence')}</button></div></form>
 </details>${reviewed?`<p class="review-record ${reviewed.decision==='reject'?'rejected':''}">${e(reviewed.reason)} · ${e(reviewed.reviewer)}</p>`:''}
 </article>`;
}
function candidateDetail(c,v){
 if(!c)return `<div class="empty">${t('Оберіть людину в черзі дослідження.','Select a person from the research queue.')}</div>`;
 const conflict=c.blockers.some(b=>b.startsWith('conflicting-'));
 const absent=v.project.criteria.filter(k=>!c.evidence.some(ev=>ev.criterionId===k.id&&ev.fresh));
 return `<div class="detail-top"><div><div class="section-label">${t('ДОСЛІДНИЦЬКА КАРТКА','RESEARCH RECORD')} · ${e(c.personKey.replace('person-',''))}</div><h3>${e(c.name)}</h3><p class="detail-sub">${imported?t('Імпортований приклад — зміст не перевірено','Imported sample — content unverified'):t('Вигадана людина','Fictional person')} · ${c.hypothesisIds.length} ${t('напрямки пошуку','research channels')} · ${c.evidence.length} ${t('твердження','claims')}</p></div><span class="badge ${c.status==='blocked'?'bad':['ready','approved'].includes(c.status)?'good':''}">${statusLabel(c.status)}</span></div>
 <div class="criteria">${v.project.criteria.map(k=>`<span class="criterion ${!c.missingCriteria.includes(k.id)?'complete':''}">${!c.missingCriteria.includes(k.id)?'✓':'○'} ${e(l(k.label))}</span>`).join('')}</div>
 ${conflict?`<div class="blocked-note">${t('Записи мають різні посилання на особу або різні імена. Передача заблокована. У пілоті дослідник мав би розділити чи виправити записи.','Records contain conflicting identities or names. Handoff is blocked. In a pilot, a researcher would need to split or correct the records.')}</div>`:absent.length?`<div class="blocked-note">${t('Потрібні нові джерела:','New sources needed:')} ${absent.map(k=>e(l(k.label))).join(', ')}.</div>`:''}
 <div class="evidence-title"><span class="section-label">${t('ДОКАЗИ ДО РІШЕННЯ','EVIDENCE BEFORE DECISION')}</span><span>${t('Свіжість спостереження від','Observation cutoff')} ${e(v.project.cutoff)}</span></div>
 ${c.evidence.map(ev=>evidenceCard(ev,v)).join('')}
 <div class="identity"><label><input type="checkbox" id="identity-check" ${c.identityConfirmed?'checked':''} ${conflict?'disabled':''}><span>${t('Я перевірив зв’язок цих записів з однією людиною в прикладі.','I checked that these sample records refer to the same person.')}</span></label><code>${c.identityRefs.map(e).join(' · ')}</code></div>
 <div class="decision-row"><p>${t('Це схвалення дослідження до передачі. Рішення про співбесіду й найм залишається за рекрутером.','This approves research for handoff. Interview and hiring decisions remain with the recruiter.')}</p><button class="button ${c.status==='approved'?'quiet':'primary'}" id="approve-button" ${!['ready','approved'].includes(c.status)?'disabled':''}>${c.status==='approved'?t('Відкликати схвалення','Revoke approval'):t('Схвалити передачу','Approve handoff')} ${arrow}</button></div>`;
}
function render(){
 const focusId=document.activeElement?.id;
 const openSources=[...document.querySelectorAll('details[open][data-source]')].map(n=>n.dataset.source);
 const v=viewSession(state);if(!v.candidates.some(c=>c.personKey===selected))selected=v.candidates[0]?.personKey;
 const c=v.candidates.find(c=>c.personKey===selected);
 const visible=v.candidates.filter(c=>(filter==='all'||c.status===filter)&&(!search||c.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())));
 document.documentElement.lang=lang;
 document.title=t('Signal Desk — Спочатку докази','Signal Desk — Evidence before decisions');
 root.innerHTML=`<div class="shell">
 <header class="topbar"><a class="brand" href="#"><span class="brand-icon"><svg width="22" height="22" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 18v-7m7 7V5m7 13V9" stroke="currentColor" stroke-width="3"/></svg></span><span class="brand-name">signal desk<small>RESEARCH WITH A REASON</small></span></a><nav class="topnav" aria-label="${t('Основна навігація','Main navigation')}"><a href="#workspace">${t('Робочий стіл','Workspace')}</a><a href="#system">${t('Архітектура','Architecture')}</a><a href="#pilot">${t('Перший пілот','First pilot')}</a><div class="language" aria-label="Language"><button data-lang="uk" aria-pressed="${lang==='uk'}">УКР</button><button data-lang="en" aria-pressed="${lang==='en'}">EN</button></div></nav></header>
 <section class="hero" data-story-beat="arrival"><div><p class="eyebrow"><span class="dot"></span>${t('НЕЗАЛЕЖНИЙ ПРОТОТИП ДЛЯ РОЗМОВИ З A-PLAYERS','AN INDEPENDENT PROTOTYPE FOR A-PLAYERS')}</p><h1>${t('Спочатку докази.<br><em>Потім рішення.</em>','Evidence first.<br><em>Then a decision.</em>')}</h1></div><div class="hero-copy"><p>${t('Зібрати розрізнені знахідки. Побачити, чого бракує. Передати рекрутеру дослідження, за кожним висновком якого стоїть джерело й рішення людини.','Bring scattered findings together. See what is missing. Give a recruiter research with a source and a human decision behind each claim.')}</p><div class="hero-actions"><button class="button primary" id="start-tour">${t('Пройти один приклад','Walk through one case')} ${arrow}</button><a class="text-link" href="${repo}" target="_blank" rel="noreferrer">${t('Код і перевірки ↗','Code & checks ↗')}</a></div></div></section>
 <div class="ribbon"><span><strong>${t('Демонстраційний режим.','Demonstration mode.')}</strong> ${imported?t('Власний приклад: вигаданість змісту не перевірено. Зміни живуть до перезавантаження.','User-supplied sample: fictionality is unverified. Changes live until reload.'):t('Усі люди й джерела вигадані. Зміни живуть у цій вкладці до перезавантаження.','All people and sources are fictional. Changes live in this tab until reload.')}</span><span class="mono version">v0.2 / ${t('без зовнішніх запитів','no external requests')}</span></div>
 <main><section id="workspace" data-story-beat="work"><div class="workspace-heading"><div><p class="eyebrow">01 / ${t('ПРАКТИЧНИЙ ПОКАЗ','WORKING DEMONSTRATION')}</p><h2>${e(l(v.project.title))}</h2></div><div class="tools"><label class="sr-only" for="scenario">${t('Сценарій','Scenario')}</label><select class="select" id="scenario">${imported?`<option value="imported" selected disabled>${t('Власний приклад','Imported sample')}</option>`:''}<option value="standard" ${scenario==='standard'&&!imported?'selected':''}>${t('Базовий пошук','Standard search')}</option><option value="conflict" ${scenario==='conflict'?'selected':''}>${t('Перевірка: конфлікт особи','Test: identity collision')}</option><option value="future-date">${t('Перевірка: дата з майбутнього','Test: future observation')}</option></select><button class="button quiet" id="reset">${t('Скинути','Reset')}</button><button class="button" id="export-button" ${!v.metrics.approved?'disabled':''}>${download} ${t('Пакет','Handoff')} (${v.metrics.approved})</button></div></div>
 ${touring?`<div class="tour"><div><strong>${t('Три хвилини: пройдіть шлях одного рішення','Three minutes: follow one decision')}</strong><p>${t('Відкрийте три докази Олени → запишіть висновок і прийміть кожен → підтвердьте особу → схваліть передачу → відкрийте пакет. Потім змініть дату внизу: схвалення скинеться.','Open Olena’s three evidence items → write your reason and accept each → confirm identity → approve the handoff → open the packet. Then change the cutoff below: approvals are cleared.')}</p></div><button class="button" id="end-tour">${t('Закрити','Dismiss')}</button></div>`:''}
 <div class="metrics">${metric(v.metrics.observations,t('знахідок<br>на вході','input<br>observations'))}${metric(v.metrics.people,t('людей<br>у черзі','people<br>in queue'))}${metric(v.metrics.mergedObservations,t('повторних<br>записів','merged<br>observations'))}${metric(v.metrics.blocked,t('конфліктів<br>особи','identity<br>conflicts'))}${metric(v.metrics.approved,t('схвалених<br>передач','approved<br>handoffs'),'emphasis')}</div>
 <div class="workbench" data-signature-moment="evidence-gate"><aside class="queue" aria-label="${t('Черга дослідження','Research queue')}"><div class="queue-head"><label class="section-label" for="search">${t('ЧЕРГА ДОСЛІДЖЕННЯ','RESEARCH QUEUE')}</label><input class="search" id="search" placeholder="${t('Знайти у прикладах…','Find in samples…')}" value="${e(search)}"><div class="filters">${[['all',t('Усі','All')],['needs-review',t('Перевірити','Review')],['blocked',t('Конфлікт','Blocked')],['approved',t('Схвалені','Approved')]].map(([id,label])=>`<button class="filter ${filter===id?'active':''}" data-filter="${id}" aria-pressed="${filter===id}">${label}</button>`).join('')}</div></div><div class="candidate-list">${visible.length?visible.map(item=>`<button class="candidate ${selected===item.personKey?'selected':''}" data-person="${e(item.personKey)}" aria-pressed="${selected===item.personKey}"><span class="avatar">${e(item.name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</span><span class="candidate-info"><strong>${e(item.name)}</strong><small>${statusLabel(item.status)}</small></span><span class="status-dot ${item.status}"></span></button>`).join(''):`<p class="empty">${t('Немає збігів у цьому фільтрі.','No matches in this filter.')}</p>`}</div><div class="queue-footer">${t('Порядок записів — без оцінки чи рейтингу людей.','Display order is not a ranking of people.')}</div></aside><div class="detail" id="candidate-detail">${candidateDetail(c,v)}</div></div>
 ${showExport&&v.exportPacket?`<section class="export-panel" id="export-panel"><h3>${t('Пакет схваленого дослідження','Approved research packet')}</h3><p>${t('Містить лише схвалених людей і прийняті актуальні докази. Завантажується локально; до TeamTailor нічого не надсилається.','Contains only approved people and accepted current evidence. Downloads locally; nothing is sent to TeamTailor.')}</p><pre>${e(JSON.stringify(v.exportPacket,null,2))}</pre><div class="export-actions"><button class="button primary" id="download-packet">${download} ${t('Завантажити JSON','Download JSON')}</button><button class="button quiet" id="close-export">${t('Згорнути','Collapse')}</button></div></section>`:''}
 <div class="settings"><label>${t('Враховувати спостереження від','Use observations from')}<br><input type="date" id="cutoff" value="${e(v.project.cutoff)}" max="${e(v.project.asOf)}"></label><button class="button" id="apply-cutoff">${t('Застосувати й скинути перевірки','Apply & invalidate reviews')}</button><button class="button quiet" id="import-project">${t('Імпортувати синтетичний приклад','Import synthetic example')}</button><button class="button quiet" id="download-project">${t('Завантажити цей приклад','Download this example')}</button><input class="file-input" type="file" id="project-file" accept=".json,application/json"></div><p class="settings-note">${t('Дата означає, коли знахідку зафіксували, а не коли людина здобула навичку. Зміна дати скидає всі перевірки, підтвердження особи й схвалення.','The date is when the observation was recorded, not when a skill was gained. Changing the cutoff clears all reviews, identity confirmations and approvals.')}</p>
 <div class="below-workbench" data-story-beat="trace"><section class="panel"><div class="panel-heading"><h3>${t('Гіпотези пошуку','Research hypotheses')}</h3><small>${t('зріз на','snapshot')} ${e(v.project.asOf)}</small></div>${v.hypotheses.map(h=>`<div class="hypothesis"><span title="${e(l(h.rationale))}">${e(l(h.label))}</span><b>${h.observations} ${t('знахідки','observations')}</b><div class="bar"><span style="width:${Math.max(4,h.observations/Math.max(1,v.metrics.observations)*100)}%"></span></div></div>`).join('')}<p class="hint">${t('Одна людина може бути знайдена в кількох каналах. Це не незалежні успіхи й не виміряний приріст ефективності.','One person can appear in several channels. These are not independent wins or measured efficiency gains.')}</p></section><section class="panel"><div class="panel-heading"><h3>${t('Журнал рішень','Decision trail')}</h3><small class="mono">${t('РЕВІЗІЯ','REVISION')} ${String(v.revision).padStart(3,'0')}</small></div>${v.events.length?`<ol class="log">${v.events.slice().reverse().slice(0,10).map(event=>`<li><span class="number">${String(event.revision).padStart(3,'0')}</span><span>${eventText(event,v)}</span></li>`).join('')}</ol>`:`<p class="hint">${t('Поки що немає рішень. Відкрийте джерело, перевірте твердження й залиште причину — тут з’явиться ваш слід.','No decisions yet. Open a source, review a claim and leave a reason — your decision will appear here.')}</p>`}<p class="hint">${t('Журнал демонструє послідовність дій у вкладці. Це не автентифікований аудит працівників.','This trail shows actions in this tab. It is not an authenticated staff audit.')}</p></section></div></section>
 <section class="system-section" id="system"><div class="section-intro"><div><p class="eyebrow">02 / ${t('ЩО ПІД КАПОТОМ','UNDER THE SURFACE')}</p><h2>${t('Висновок має<br>витримати перевірку.','A conclusion should<br>survive inspection.')}</h2></div><p>${t('Інтерфейс керує одним ядром правил. Воно перевіряє вхідні дані, зберігає рішення з причинами й повторно оцінює можливість передачі після кожної зміни. Ті самі правила працюють у браузері та тестах.','The interface drives one policy engine. It validates input, records decisions with reasons, and re-evaluates handoff eligibility after every change. The same rules run in the browser and in tests.')}</p></div><div class="architecture">${[
 [t('01 / ВХІД','01 / INPUT'),t('Пропозиція ≠ доказ','A proposal needs evidence'),t('Критерії, гіпотези й джерела проходять перевірку структури та дат. Цитата має бути в документі.','Criteria, hypotheses and sources pass structure and date checks. A quote must occur in its source.')],
 [t('02 / ОБ’ЄДНАННЯ','02 / GROUPING'),t('Зберегти походження','Keep the provenance'),t('Об’єднані знахідки зберігають власні джерела. Конфлікт особи блокує передачу.','Merged findings keep their own sources. An identity conflict blocks the handoff.')],
 [t('03 / ЛЮДИНА','03 / HUMAN'),t('Перевірити й вирішити','Inspect, then decide'),t('Людина перевіряє кожен потрібний доказ і зв’язок записів. Відсутнє підтвердження лишається видимим.','A person checks the required evidence and record identity. Missing confirmation stays visible.')],
 [t('04 / ПЕРЕДАЧА','04 / HANDOFF'),t('Перенести причину','Carry the reason'),t('Локальний пакет містить прийняті докази й журнал. Зміна умов скасовує попередні перевірки.','A local packet carries accepted evidence and the trail. Changed conditions invalidate earlier reviews.')]
 ].map(([num,title,body])=>`<article class="arch-step"><div class="num">${num}</div><h3>${title}</h3><p>${body}</p></article>`).join('')}</div><div class="system-boundaries"><span>${t('Межа демонстрації: без живого пошуку, виклику мовної моделі, підключення до Brain або TeamTailor.','Demo boundary: no live sourcing, language model calls, Brain or TeamTailor connection.')}</span><a href="${repo}/blob/main/docs/architecture.md" target="_blank" rel="noreferrer">${t('Повна архітектура ↗','Full architecture ↗')}</a></div></section>
 <section class="system-section" id="pilot"><div class="section-intro"><div><p class="eyebrow">03 / ${t('РОЗМОВА ПРО РЕАЛЬНУ РОБОТУ','THE CONVERSATION ABOUT REAL WORK')}</p><h2>${t('Один пошук.<br>Перевірний результат.','One search.<br>An inspectable result.')}</h2></div><p>${t('Прототип перевіряє спосіб роботи. Користь для A-Players можна встановити тільки на погодженому пілоті з їхніми критеріями, даними та початковими вимірами.','The prototype tests a way of working. Its value to A-Players can only be established in an agreed pilot with their criteria, data and baseline measurements.')}</p></div><div class="notes-grid"><div class="note"><h3>${t('Як я підійшов би до першого місяця','How I would approach the first month')}</h3><ol class="pilot-list"><li><div><strong>${t('Побачити роботу зсередини','Observe the actual work')}</strong><small>${t('Перші 2–3 тижні — спостерігати за живими пошуками разом із рекрутерами, як передбачено в ролі.','First 2–3 weeks: shadow live searches with recruiters, as described in the role.')}</small></div></li><li><div><strong>${t('Вибрати одну втрату часу','Pick one source of lost time')}</strong><small>${t('Пошук, перевірка чи передача даних? Визначити початковий рівень й один критерій успіху.','Sourcing, verification or handoff? Establish a baseline and one success measure.')}</small></div></li><li><div><strong>${t('Провести малий погоджений пілот','Run a small agreed pilot')}</strong><small>${t('Один пошук, обмежені доступи, рішення людини. Порівняти час і частку прийнятих знахідок.','One search, limited access, human decisions. Compare elapsed time and accepted findings.')}</small></div></li></ol></div><div class="note"><h3>${t('Чому я приніс цей прототип','Why I brought this prototype')}</h3><p>${t('Я Артур. Працюю в будівництві й досліджую, як створювати корисні системи разом із ШІ. Цей прототип розроблено за допомогою Codex. Він показує підхід до задачі; мою самостійність у технічній роботі треба перевіряти окремо.','I’m Artur. I work in construction and explore building useful systems with AI. This prototype was developed with Codex. It demonstrates an approach to a problem; my independent technical ability needs to be assessed separately.')}</p><p>${t('На зустрічі хочу зрозуміти, де вашій команді найбільше потрібна допомога, й разом визначити маленький результат, який справді варто перевірити.','In our conversation, I want to understand where your team most needs help and agree on a small result that is worth testing.')}</p><a class="text-link" href="https://aplayers.na.teamtailor.com/jobs/617015-talent-engineer-ai-automation-a-players" target="_blank" rel="noreferrer">${t('Публічний опис ролі, на якому базується задум ↗','The public role brief behind this proposal ↗')}</a></div></div></section></main>
 <footer class="footer"><span>Signal Desk · ${t('Незалежний прототип Артура, створений із Codex. Не продукт A-Players.','Artur’s independent prototype, built with Codex. Not an A-Players product.')}</span><div class="footer-links"><a href="${repo}/blob/main/docs/limits.md" target="_blank" rel="noreferrer">${t('Межі','Limits')}</a><a href="${repo}" target="_blank" rel="noreferrer">GitHub ↗</a></div></footer></div>`;
 for(const node of document.querySelectorAll('details[data-source]')) if(openSources.includes(node.dataset.source))node.open=true;
 bind(v,c);
 if(focusId)document.getElementById(focusId)?.focus({preventScroll:true});
}
function saveJSON(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function bind(v,c){
 document.querySelectorAll('[data-lang]').forEach(n=>n.onclick=()=>{lang=n.dataset.lang;const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);render();});
 document.querySelectorAll('[data-person]').forEach(n=>n.onclick=()=>{selected=n.dataset.person;render();if(innerWidth<761)document.querySelector('#candidate-detail').scrollIntoView({block:'start'});});
 document.querySelectorAll('[data-filter]').forEach(n=>n.onclick=()=>{filter=n.dataset.filter;render();document.querySelector(`[data-filter="${filter}"]`).focus();});
 document.querySelector('#search').oninput=event=>{const pos=event.target.selectionStart;search=event.target.value;render();const n=document.querySelector('#search');n.focus();n.setSelectionRange(pos,pos);};
 document.querySelector('#scenario').onchange=event=>{try{const next=createSession(demoProject(event.target.value));state=next;imported=false;scenario=event.target.value;selected='person-olena';showExport=false;filter='all';search='';render();}catch(error){event.target.value=imported?'imported':scenario;notify(t('Вхідні дані відхилено. Поточна сесія збережена. Причина: ','Input rejected. Current session preserved. Reason: ')+error.message);}};
 document.querySelector('#reset').onclick=()=>{state=createSession(v.project);selected='';showExport=false;filter='all';search='';render();notify(t('Новий показ почато.','A fresh demonstration started.'));};
 document.querySelector('#start-tour').onclick=()=>{state=createSession(demoProject());imported=false;scenario='standard';showExport=false;touring=true;selected='person-olena';filter='all';search='';render();document.querySelector('#workspace').scrollIntoView({block:'start'});};
 document.querySelector('#end-tour')?.addEventListener('click',()=>{touring=false;render();});
 document.querySelectorAll('[data-review-form]').forEach(form=>form.onsubmit=event=>{event.preventDefault();const id=form.dataset.reviewForm;const reason=new FormData(form).get('reason').trim();const decision=event.submitter?.value;if(!reason){form.querySelector('input').focus();return;}if(act({type:'review',evidenceId:id,decision,reason,reviewer:reviewer()})){const next=document.getElementById(`reason-${id}`);next?.focus();notify(t('Рішення записано.','Decision recorded.'));}});
 document.querySelector('#identity-check')?.addEventListener('change',event=>act({type:'identity',personKey:c.personKey,confirmed:event.target.checked,reviewer:reviewer()}));
 document.querySelector('#approve-button')?.addEventListener('click',()=>{if(act({type:c.status==='approved'?'revoke':'approve',personKey:c.personKey,reviewer:reviewer()}))notify(c.status==='approved'?t('Схвалення відкликано.','Approval revoked.'):t('Передачу схвалено. Відкрийте пакет у правому верхньому куті.','Handoff approved. Open the packet at the top right.'));});
 document.querySelector('#export-button').onclick=()=>{showExport=!showExport;render();document.querySelector('#export-panel')?.scrollIntoView({block:'center'});};
 document.querySelector('#close-export')?.addEventListener('click',()=>{showExport=false;render();document.querySelector('#export-button').focus();});
 document.querySelector('#download-packet')?.addEventListener('click',()=>{try{saveJSON(exportHandoff(state),'signal-desk-handoff.json');}catch(error){notify(error.message);}});
 document.querySelector('#apply-cutoff').onclick=()=>{if(act({type:'setCutoff',cutoff:document.querySelector('#cutoff').value})){showExport=false;render();notify(t('Дату змінено. Попередні перевірки, підтвердження й схвалення скинуто.','Cutoff changed. Prior reviews, confirmations and approvals cleared.'));}};
 document.querySelector('#download-project').onclick=()=>saveJSON(v.project,'signal-desk-project.json');
 document.querySelector('#import-project').onclick=()=>document.querySelector('#project-file').click();
 document.querySelector('#project-file').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>500000)throw Error('file exceeds 500 KB');const project=JSON.parse(await file.text());const next=createSession(project);state=next;imported=true;scenario='standard';showExport=false;selected='';filter='all';search='';render();notify(t('Приклад завантажено. Перевірки починаються заново.','Example loaded. Reviews start fresh.'));}catch(error){notify(t('Імпорт відхилено: ','Import rejected: ')+error.message);}};
}
render();
