import { validateResearchReport } from './research.js?v=0.9.0';
import { renderResearchReview } from './research-review-view.js?v=0.9.0';
import { researchReviewPacket } from './research-review.js?v=0.9.0';
import { renderPilotFeedback } from './pilot-feedback-view.js?v=0.9.0';

const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const laneNames = {
  'agent-orchestration': ['Оркестрація агентів', 'Agent orchestration'],
  'ts-agent-tooling': ['Інструменти агентів на TypeScript', 'TypeScript agent tooling'],
  'programmable-editor': ['Програмовані редактори на React', 'Programmable React editors'],
  'agent-recovery': ['Відновлення й надійність агентів', 'Agent recovery and reliability'],
  'video-timeline': ['Відеотаймлайн і редактор', 'Video timeline and editor']
};

export function renderResearch(input, lang = 'uk', { loading = false, imported = true, error = '', staticView = false, reviewSession = null, inspections = {}, pilotFeedback = null } = {}) {
  const report = input === null ? null : validateResearchReport(input);
  const t = (uk, en) => lang === 'en' ? en : uk, e = escapeHTML;
  const laneLabel = lane => laneNames[lane.id]?.[lang === 'en' ? 1 : 0] || lane.label;
  const statusLabel = status => ({ ok: t('Дані отримано', 'Data received'), empty: t('Акаунтів не виявлено', 'No accounts surfaced'), partial: t('Отримано частину даних', 'Partial data received'), error: t('Дані не отримано', 'No usable data received') }[status] || t('Неповні дані', 'Incomplete data'));
  const runStatus = status => ({ complete: t('Збір завершено', 'Collection complete'), partial: t('Частковий результат', 'Partial result'), failed: t('Збір не вдався', 'Collection failed') }[status]);
  return `<section class="research-run" id="research" aria-labelledby="research-heading">
    <p class="eyebrow">${t('ВІД РОЛІ ДО ПУБЛІЧНОГО ДЖЕРЕЛА', 'FROM A ROLE TO A PUBLIC SOURCE')}</p>
    <h2 id="research-heading" tabindex="-1">${t('Пошуковий прохід, який можна повторити', 'A research pass you can repeat')}</h2>
    <p class="research-intro">${t('Приклад для ролі Senior Agentic Software Engineer у Poolday. Пошук перевіряє п’ять технічних напрямів, включно з відеотаймлайном, і зберігає до двох злитих PR на акаунт у напрямі. Контрольний прохід показує останні коміти трьох репозиторіїв.', 'An example for Poolday’s Senior Agentic Software Engineer role. The search checks five technical lanes, including video timeline work, and keeps up to two merged PRs per account per lane. The comparison pass reads recent commits in three repositories.')}</p>
    <p class="research-boundary">${t('Це початкові сліди для дослідження. Злитий PR або коміт не доводить кваліфікацію, особистий внесок чи готовність людини до розмови. Пошук обмежений обраними репозиторіями; його результати не ранжують людей.', 'These are initial research leads. A merged PR or commit does not establish proficiency, personal contribution or willingness to talk. Discovery is limited to selected repositories; results do not rank people.')}</p>
    ${staticView ? '' : `<div class="research-actions"><button class="button primary" id="collect-role-search" ${loading ? 'disabled' : ''}>${loading ? t('Шукаю відкриті роботи…', 'Searching public work…') : t('Пошук за роллю: злиті PR', 'Role search: merged PRs')}</button><button class="button quiet" id="collect-research" ${loading ? 'disabled' : ''}>${t('Контроль: останні коміти', 'Comparison: recent commits')}</button><button class="button quiet" id="import-research" ${loading ? 'disabled' : ''}>${t('Відкрити збережений прохід', 'Open a saved run')}</button><input type="file" class="file-input" id="research-file" accept=".json,application/json">${report ? `<button class="button" id="download-research">${t('Повний звіт без оцінок', 'Full unreviewed brief')}</button><button class="button quiet" id="download-research-note">${t('Контекст проходу без оцінок', 'Unreviewed run context')}</button><button class="button quiet" id="download-research-json">JSON</button>` : ''}</div><p class="research-footnote">${t('Пошук за роллю читає до п’яти обмежених запитів GitHub до злитих PR, перевіряє дату, тип автора та назву технічної зміни. Точні запити й повний облік переглянутих рядків видимі. Після HTTP 403/429 решта запитів зупиняється. Файли читаються лише за натисканням.', 'Role search makes up to five bounded GitHub merged-PR queries and checks merge date, author type and technical change title. Exact queries and full scanned-row accounting are visible. Later queries stop after HTTP 403/429. Files are read only on click.')}</p>`}
    ${error ? `<p class="blocked-note" role="alert">${e(error)}</p>` : ''}
    ${loading ? `<p class="research-progress" role="status">${t('Перевіряються напрями пошуку. Ручна черга залишається доступною.', 'Checking research lanes. The manual queue remains available.')}</p>` : ''}
    ${report ? `<div class="research-summary"><div><strong>${report.leads.length}</strong><span>${t('унікальних публічних акаунтів', 'distinct public accounts')}</span></div><div><strong>${report.lanes.filter(lane => ['ok', 'empty', 'partial'].includes(lane.status)).length}/${report.lanes.length}</strong><span>${t('напрямів із відповіддю', 'lanes with a response')}</span></div><div><strong>${(report.run.elapsedMs / 1000).toFixed(2)} ${t('с', 's')}</strong><span>${t('час цього збору даних', 'elapsed collection time')}</span></div></div>
      <p class="research-footnote">${t('Зафіксовано', 'Observed')}: ${e(report.run.observedAt)} · ${t('Стан проходу', 'Run status')}: ${runStatus(report.run.status)}.${report.run.plannedRequests ? ` ${t('Запитів зроблено', 'Requests made')}: ${report.run.requests}/${report.run.plannedRequests}. ${t('Збережено змін для перевірки', 'Changes retained for review')}: ${report.leads.reduce((sum, lead) => sum + lead.evidence.length, 0)}.` : ''} ${imported ? t('Відкрито з файлу; походження файлу не підтверджено.', 'Opened from a file; file origin is unverified.') : t('Результат запитів цього проходу.', 'Results from this collection run.')} ${t('Це час збору, а не час до придатного кандидата. Оцінки рекрутера ще немає.', 'This is collection time, not time to a qualified candidate. Recruiter acceptance has not been measured.')}</p>
      <a class="text-link" href="${e(report.role.url)}" target="_blank" rel="noreferrer">${t('Публічна роль, на якій базується приклад ↗', 'The public role behind this example ↗')}</a>
      <div class="research-lanes">${report.lanes.map(lane => `<article><h3>${e(laneLabel(lane))}</h3><p>${e(lane.repo)}</p><strong>${statusLabel(lane.status)}</strong><p>${lane.leadIds.length} ${t('акаунтів', 'accounts')} · ${lane.observations} ${t('збережених змін', 'retained changes')}</p><p>${t('Переглянуто', 'Scanned')} ${lane.scanned} · ${t('пропущено', 'skipped')} ${lane.skipped} · ${t('відхилено як помилкові', 'malformed')} ${lane.rejected}${lane.duplicates !== undefined ? ` · ${t('дублі', 'duplicates')} ${lane.duplicates} · ${t('поза лімітом', 'over cap')} ${lane.capped}` : ''}</p><a href="${e(lane.queryUrl)}" target="_blank" rel="noreferrer">${t('Точний запит ↗', 'Exact query ↗')}</a>${lane.error ? `<details><summary>${t('Причина неповноти', 'Why this is incomplete')}</summary><p>${lane.error === 'not requested after HTTP 403/429' ? t('Не запитували після відповіді GitHub HTTP 403/429.', 'Not requested after GitHub HTTP 403/429.') : e(lane.error)}</p></details>` : ''}</article>`).join('')}</div>
      ${!staticView && reviewSession ? renderResearchReview(reviewSession, lang, imported, inspections) : ''}
      ${!staticView ? renderPilotFeedback(pilotFeedback, lang, Boolean(reviewSession && researchReviewPacket(reviewSession, imported))) : ''}
      ${report.leads.length ? `<h3 class="research-raw-title">${t('Повний список зібраних слідів', 'Full list of collected signals')}</h3><div class="research-leads">${report.leads.map(lead => `<article class="research-lead" data-research-lead="${e(lead.id)}"><header><h3><a href="${e(lead.profileUrl)}" target="_blank" rel="noreferrer">@${e(lead.handle)} ↗</a></h3><span>${t('Потребує перевірки', 'Needs research')}</span></header><p>${t('Виявлено через', 'Surfaced through')}: ${lead.hypothesisIds.map(id => e(laneNames[id]?.[lang === 'en' ? 1 : 0] || id)).join(' · ')}</p><h4>${t('Що можна перевірити зараз', 'What can be inspected now')}</h4><p>${t('GitHub пов’язує цей акаунт із такими публічними змінами. Відкрийте саму зміну, щоб оцінити її зміст і роль автора.', 'GitHub associates this account with these public changes. Open each change to assess its content and the author’s role.')}</p><ul>${lead.evidence.map(ev => `<li><a href="${e(ev.url)}" target="_blank" rel="noreferrer">${e(ev.repository)} ↗</a><p>${e(ev.title)}</p><small>${ev.kind === 'github-pr' ? t('Злито PR', 'PR merged') : t('Дата коміту', 'Commit date')}: ${e(ev.mergedAt ?? ev.committedAt)}</small></li>`).join('')}</ul><div class="research-next"><h4>${t('Що лишається невідомим', 'What remains unknown')}</h4><p>${t('Глибину відповідного досвіду, професійний стаж, можливість працювати в потрібному регіоні, доступність та інтерес до ролі. Публічний пошук змін у коді цього не встановлює.', 'Depth of relevant experience, professional tenure, regional work eligibility, availability and interest. Public code-change discovery does not establish these.')}</p></div></article>`).join('')}</div>` : `<p class="blocked-note">${t('Цей прохід не дав акаунтів для подальшого дослідження. Перегляньте стани джерел; порожній результат не доводить відсутність людей на ринку.', 'This run yielded no accounts for further research. Inspect the lane statuses; an empty run does not establish market scarcity.')}</p>`}
      <p class="research-footnote">${t('Однакові GitHub ID об’єднуються. Збіг імен не використовується для зіставлення осіб. Системи компанії, приватні контакти й повідомлення не залучені.', 'Records sharing a GitHub ID are grouped. Names are not used to resolve identity. Company systems, private contact details and messaging are not involved.')}</p>` : ''}
    ${!staticView && !report ? renderPilotFeedback(pilotFeedback, lang, false) : ''}
  </section>`;
}

export function researchDocument(report, lang = 'uk', imported = true) {
  const content = renderResearch(report, lang, { staticView: true, imported });
  const language = lang === 'en' ? 'en' : 'uk';
  return `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Signal Desk — ${language === 'uk' ? 'Пошуковий прохід' : 'Research brief'}</title><style>body{margin:0;padding:24px;background:#f4f3ed;color:#1b3029;font:15px/1.6 system-ui,sans-serif}main{max-width:1050px;margin:auto}h2{font-size:32px;line-height:1.2}a{color:#255c43}p{margin:10px 0}.eyebrow{font-size:12px;letter-spacing:1px}.research-summary,.research-lanes{display:flex;gap:16px;flex-wrap:wrap;margin:24px 0}.research-summary>div,.research-lanes>article{flex:1;min-width:220px;padding:18px;border:1px solid #d6dcd1;border-radius:10px;background:#fffefa}.research-summary strong{display:block;font-size:26px}.research-summary span{font-size:12px}.research-footnote,.research-boundary{font-size:13px;color:#58675f}.research-lead{padding:24px;margin:20px 0;border:1px solid #d6dcd1;border-radius:12px;background:#fffefa;overflow-wrap:anywhere}.research-lead header{display:flex;flex-wrap:wrap;justify-content:space-between;gap:12px}.research-lead h3{margin:0}.research-lead header span{color:#79541c}.research-lead li{margin:18px 0}.research-lead small{color:#58675f}.research-next{background:#e9efe5;padding:16px;border-radius:8px}.research-next h4{margin:0}.blocked-note{padding:18px;background:#f5eddb}summary{cursor:pointer}@media(max-width:600px){body{padding:12px}.research-lead{padding:18px}h2{font-size:26px}}@media print{.research-lead{break-inside:avoid}}</style></head><body><main>${content}</main></body></html>`;
}
