import { validateResearchReport } from './research.js?v=0.10.0';
import { renderResearchReview } from './research-review-view.js?v=0.10.0';
import { researchReviewPacket } from './research-review.js?v=0.10.0';
import { renderPilotFeedback } from './pilot-feedback-view.js?v=0.10.0';

const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const laneNames = {
  'agent-orchestration': ['Оркестрація агентів', 'Agent orchestration'],
  'ts-agent-tooling': ['Інструменти агентів на TypeScript', 'TypeScript agent tooling'],
  'programmable-editor': ['Програмовані редактори на React', 'Programmable React editors'],
  'agent-recovery': ['Відновлення й надійність агентів', 'Agent recovery and reliability'],
  'video-timeline': ['Відеотаймлайн і редактор', 'Video timeline and editor']
};
function renderScreenedOut(lane, t, e) {
  if (!Array.isArray(lane.screenedOut)) return lane.skipped
    ? `<p class="research-footnote">${t('Цей старіший прохід не зберіг посилання на окремі пропущені PR.', 'This older run did not retain links to individual skipped PRs.')}</p>` : '';
  if (!lane.skipped) return '';
  const reason = code => ({
    'technical-prefix-required': t('назва не має потрібного технічного префікса', 'title lacks the required technical prefix'),
    'title-context-rule': t('назва не пройшла правило теми', 'title failed the topic rule'),
    'outside-merge-window': t('поза вікном дати злиття', 'outside the merge-date window')
  }[code]);
  return `<details class="research-screened"><summary>${t('Відсіяні з точним посиланням', 'Screened out with exact links')} ${lane.screenedOut.length}/${lane.skipped}</summary><p class="research-footnote">${t('Ці PR не є знахідками для передачі. Інші пропуски до цього списку не потрапили.', 'These PRs are not handoff leads. Other skipped rows are not in this list.')}</p><ul>${lane.screenedOut.map(item => `<li><a href="${e(item.url)}" target="_blank" rel="noreferrer">${e(item.title)} ↗</a><small>${e(reason(item.reason))} · ${e(item.mergedAt)}</small></li>`).join('')}</ul></details>`;
}

export function renderResearch(input, lang = 'uk', { loading = false, imported = true, showcase = false, pendingLiveReport = null, error = '', staticView = false, reviewSession = null, inspections = {}, pilotFeedback = null } = {}) {
  const report = input === null ? null : validateResearchReport(input);
  const pending = pendingLiveReport === null ? null : validateResearchReport(pendingLiveReport);
  const t = (uk, en) => lang === 'en' ? en : uk, e = escapeHTML;
  const laneLabel = lane => laneNames[lane.id]?.[lang === 'en' ? 1 : 0] || lane.label;
  const statusLabel = status => ({ ok: t('Дані отримано', 'Data received'), empty: t('Акаунтів не виявлено', 'No accounts surfaced'), partial: t('Отримано частину даних', 'Partial data received'), error: t('Дані не отримано', 'No usable data received') }[status] || t('Неповні дані', 'Incomplete data'));
  const runStatus = status => ({ complete: t('Збір завершено', 'Collection complete'), partial: t('Частковий результат', 'Partial result'), failed: t('Збір не вдався', 'Collection failed') }[status]);
  const featured = showcase ? report?.leads.find(lead => lead.evidence.filter(item => item.repository === 'remotion-dev/remotion').length === 2) : null;
  const videoSources = featured?.evidence.filter(item => item.repository === 'remotion-dev/remotion') ?? [];
  return `<section class="research-run" id="research" aria-labelledby="research-heading">
    <p class="eyebrow">${t('ВІД РОЛІ ДО ПУБЛІЧНОГО ДЖЕРЕЛА', 'FROM A ROLE TO A PUBLIC SOURCE')}</p>
    <h2 id="research-heading" tabindex="-1">${t('Від ролі до рішення — з відкритими джерелами', 'From role to decision — with open sources')}</h2>
    <p class="research-intro">${t('Приклад для ролі Senior Agentic Software Engineer у Poolday. Пошук починає з відеотаймлайну, далі перевіряє ще чотири технічні напрями й зберігає до двох злитих PR на акаунт у напрямі. Контрольний прохід показує останні коміти трьох репозиторіїв.', 'An example for Poolday’s Senior Agentic Software Engineer role. The search starts with video timeline work, then checks four more technical lanes and keeps up to two merged PRs per account per lane. The comparison pass reads recent commits in three repositories.')}</p>
    <div class="research-path" aria-label="${t('Як працює приклад', 'How this example works')}"><article><span>01 / ${t('РОЛЬ', 'ROLE')}</span><strong>${t('AI відеоредактор + агенти TypeScript', 'AI video editor + TypeScript agents')}</strong><p>${t('З опису ролі вибрано п’ять перевірних технічних напрямів.', 'Five inspectable technical lanes come from the role brief.')}</p></article><article><span>02 / ${t('СЛІД', 'SOURCE')}</span><strong>${t('Точний PR і змінені файли', 'Exact PR and changed files')}</strong><p>${t('Два PR одного GitHub ID залишаються двома джерелами, не двома людьми.', 'Two PRs from one GitHub ID are two sources, not two people.')}</p></article><article><span>03 / ${t('РІШЕННЯ', 'DECISION')}</span><strong>${t('Причина й наступна перевірка людини', 'A reason and a human next step')}</strong><p>${t('Оцінка сліду відкриває тільки подальше дослідження.', 'A source review permits further research only.')}</p></article></div>
    <p class="research-boundary">${t('Це початкові сліди для дослідження. Злитий PR або коміт не доводить кваліфікацію, особистий внесок чи готовність людини до розмови. Пошук обмежений обраними репозиторіями; його результати не ранжують людей.', 'These are initial research leads. A merged PR or commit does not establish proficiency, personal contribution or willingness to talk. Discovery is limited to selected repositories; results do not rank people.')}</p>
    ${staticView ? '' : `<div class="research-actions"><button class="button primary" id="open-showcase" ${loading || showcase ? 'disabled' : ''}>${loading ? t('Відкриваю знімок…', 'Opening the snapshot…') : showcase ? t('Зафіксований прохід відкрито', 'Recorded pass is open') : t('Відкрити зафіксований прохід', 'Open the recorded pass')}</button><button class="button quiet" id="collect-role-search" ${loading ? 'disabled' : ''}>${t('Запустити живий пошук', 'Run live search')}</button><button class="button quiet" id="collect-research" ${loading ? 'disabled' : ''}>${t('Контроль: останні коміти', 'Comparison: recent commits')}</button><button class="button quiet" id="import-research" ${loading ? 'disabled' : ''}>${t('Відкрити збережений прохід', 'Open a saved run')}</button><input type="file" class="file-input" id="research-file" accept=".json,application/json">${report ? `<button class="button" id="download-research">${t('Повний звіт без оцінок', 'Full unreviewed brief')}</button><button class="button quiet" id="download-research-note">${t('Контекст проходу без оцінок', 'Unreviewed run context')}</button><button class="button quiet" id="download-research-json">JSON</button>` : ''}</div><p class="research-footnote">${t('Зафіксований прохід читається з цього сайту без запитів до GitHub. Живий пошук окремо робить до п’яти публічних запитів; після HTTP 403/429 решта зупиняється.', 'The recorded pass loads from this site without GitHub requests. Live search separately makes up to five public queries and stops later requests after HTTP 403/429.')}</p>`}
    ${error ? `<p class="blocked-note" role="alert">${e(error)}</p>` : ''}
    ${loading ? `<p class="research-progress" role="status">${t('Перевіряються напрями пошуку. Ручна черга залишається доступною.', 'Checking research lanes. The manual queue remains available.')}</p>` : ''}
    ${!staticView && pending ? `<section class="research-attempt" aria-labelledby="research-attempt-title"><p class="eyebrow">${t('НОВИЙ ЖИВИЙ ПРОХІД ОКРЕМО', 'A SEPARATE NEW LIVE RUN')}</p><h3 id="research-attempt-title">${runStatus(pending.run.status)} · ${pending.lanes.filter(lane => ['ok', 'empty', 'partial'].includes(lane.status)).length}/${pending.lanes.length} ${t('напрямів', 'lanes')}</h3><p>${t('Запитів', 'Requests')}: ${pending.run.requests}/${pending.run.plannedRequests ?? pending.run.requests} · ${t('GitHub ID', 'GitHub IDs')}: ${pending.leads.length} · ${t('збережених змін', 'retained changes')}: ${pending.leads.reduce((sum, lead) => sum + lead.evidence.length, 0)} · ${e(pending.run.observedAt)}.</p>${pending.lanes.some(lane => lane.error) ? `<p>${t('Неповні напрями', 'Incomplete lanes')}: ${pending.lanes.filter(lane => lane.error).map(lane => `${e(laneLabel(lane))} (${e(lane.error)})`).join(' · ')}.</p>` : ''}<p>${t('Поточний прохід і записані рішення не змінено. Новий результат можна завантажити або відкрити окремим рішенням.', 'The current run and its recorded decisions remain unchanged. Download the new result or explicitly open it.')}</p><div class="research-actions"><button class="button" id="download-live-attempt">${t('JSON нового проходу', 'New run JSON')}</button><button class="button primary" id="adopt-live-run" ${pending.leads.length ? '' : 'disabled'}>${t('Відкрити новий результат', 'Open the new result')}</button></div></section>` : ''}
    ${showcase && report ? `<div class="research-snapshot" role="note"><strong>${t('Знімок публічного GitHub API від', 'Public GitHub API snapshot from')} ${e(report.run.observedAt)}</strong><p>${t('Файл цього релізу збігається з зафіксованим SHA-256. Це перевірка цілісності файла, а не незалежне підтвердження авторства, кваліфікації чи поточного стану GitHub. Новий збір запускається окремою кнопкою.', 'This release file matches its pinned SHA-256. That checks file integrity, not authorship, qualification or current GitHub state. A fresh collection uses the separate button.')}</p>${staticView ? '' : `<a href="data/poolday-public-pass-2026-09-28.json" target="_blank" rel="noreferrer">${t('Відкрити точний JSON знімка ↗', 'Open the exact snapshot JSON ↗')}</a> <a href="docs/meeting-brief.${lang === 'en' ? 'en' : 'uk'}.html" download>${t('Зберегти офлайн-картку ↓', 'Save offline brief ↓')}</a>`}</div>` : ''}
    ${report ? `<div class="research-summary"><div><strong>${report.leads.length}</strong><span>${t('унікальних публічних акаунтів', 'distinct public accounts')}</span></div><div><strong>${report.lanes.filter(lane => ['ok', 'empty', 'partial'].includes(lane.status)).length}/${report.lanes.length}</strong><span>${t('напрямів із відповіддю', 'lanes with a response')}</span></div><div><strong>${(report.run.elapsedMs / 1000).toFixed(2)} ${t('с', 's')}</strong><span>${t('час цього збору даних', 'elapsed collection time')}</span></div></div>
      <p class="research-footnote">${t('Зафіксовано', 'Observed')}: ${e(report.run.observedAt)} · ${t('Стан проходу', 'Run status')}: ${runStatus(report.run.status)}.${report.run.plannedRequests ? ` ${t('Запитів зроблено', 'Requests made')}: ${report.run.requests}/${report.run.plannedRequests}. ${t('Збережено змін для перевірки', 'Changes retained for review')}: ${report.leads.reduce((sum, lead) => sum + lead.evidence.length, 0)}.` : ''} ${showcase ? t('Архівний файл релізу; зовнішню правдивість джерел не підтверджено.', 'Release-bundled archive; external source truth is unverified.') : imported ? t('Відкрито з файлу; походження файлу не підтверджено.', 'Opened from a file; file origin is unverified.') : t('Результат запитів цього проходу.', 'Results from this collection run.')} ${t('Це час збору, а не час до придатного кандидата. Оцінки рекрутера ще немає.', 'This is collection time, not time to a qualified candidate. Recruiter acceptance has not been measured.')}</p>
      <a class="text-link" href="${e(report.role.url)}" target="_blank" rel="noreferrer">${t('Публічна роль, на якій базується приклад ↗', 'The public role behind this example ↗')}</a>
      ${featured ? `<section class="research-case" aria-labelledby="research-case-title"><p class="eyebrow">${t('ОДИН ПЕРЕВІРНИЙ ПРИКЛАД', 'ONE INSPECTABLE EXAMPLE')}</p><h3 id="research-case-title">${t('Один GitHub ID. Два PR про відеотаймлайн.', 'One GitHub ID. Two video-timeline PRs.')}</h3><p>${t('Це два різні публічні сліди роботи одного акаунта. Архів містить обмежений список змінених файлів для кожного. Вони ще не відповідають на питання про особистий внесок і придатність до ролі.', 'These are two public work traces from one account. The archive includes a bounded changed-file list for each. They do not establish individual contribution or role fit.')}</p><div class="research-case-links">${videoSources.map(item => `<a href="${e(item.url)}" target="_blank" rel="noreferrer">${e(item.repository)} · PR #${item.number} ↗</a>`).join('')}</div>${staticView ? '' : `<a class="text-link" href="#research-review-title">${t('Нижче — файли, причина й людське рішення ↓', 'Below: files, reason and human decision ↓')}</a>`}</section>` : ''}
      <div class="research-lanes">${report.lanes.map(lane => `<article><h3>${e(laneLabel(lane))}</h3><p>${e(lane.repo)}</p><strong>${statusLabel(lane.status)}</strong><p>${lane.leadIds.length} ${t('акаунтів', 'accounts')} · ${lane.observations} ${t('збережених змін', 'retained changes')}</p><p>${t('Переглянуто', 'Scanned')} ${lane.scanned} · ${t('пропущено', 'skipped')} ${lane.skipped} · ${t('відхилено як помилкові', 'malformed')} ${lane.rejected}${lane.duplicates !== undefined ? ` · ${t('дублі', 'duplicates')} ${lane.duplicates} · ${t('поза лімітом', 'over cap')} ${lane.capped}` : ''}</p><a href="${e(lane.queryUrl)}" target="_blank" rel="noreferrer">${t('Точний запит ↗', 'Exact query ↗')}</a>${renderScreenedOut(lane,t,e)}${lane.error ? `<details><summary>${t('Причина неповноти', 'Why this is incomplete')}</summary><p>${lane.error === 'not requested after HTTP 403/429' ? t('Не запитували після відповіді GitHub HTTP 403/429.', 'Not requested after GitHub HTTP 403/429.') : e(lane.error)}</p></details>` : ''}</article>`).join('')}</div>
      ${!staticView && reviewSession ? renderResearchReview(reviewSession, lang, imported, inspections) : ''}
      ${!staticView ? renderPilotFeedback(pilotFeedback, lang, Boolean(reviewSession && researchReviewPacket(reviewSession, imported))) : ''}
      ${report.leads.length ? `<h3 class="research-raw-title">${t('Повний список зібраних слідів', 'Full list of collected signals')}</h3><div class="research-leads">${report.leads.map(lead => `<article class="research-lead" data-research-lead="${e(lead.id)}"><header><h3><a href="${e(lead.profileUrl)}" target="_blank" rel="noreferrer">@${e(lead.handle)} ↗</a></h3><span>${t('Потребує перевірки', 'Needs research')}</span></header><p>${t('Виявлено через', 'Surfaced through')}: ${lead.hypothesisIds.map(id => e(laneNames[id]?.[lang === 'en' ? 1 : 0] || id)).join(' · ')}</p><h4>${t('Що можна перевірити зараз', 'What can be inspected now')}</h4><p>${t('GitHub пов’язує цей акаунт із такими публічними змінами. Відкрийте саму зміну, щоб оцінити її зміст і роль автора.', 'GitHub associates this account with these public changes. Open each change to assess its content and the author’s role.')}</p><ul>${lead.evidence.map(ev => `<li><a href="${e(ev.url)}" target="_blank" rel="noreferrer">${e(ev.repository)} ↗</a><p>${e(ev.title)}</p><small>${ev.kind === 'github-pr' ? t('Злито PR', 'PR merged') : t('Дата коміту', 'Commit date')}: ${e(ev.mergedAt ?? ev.committedAt)}</small></li>`).join('')}</ul><div class="research-next"><h4>${t('Що лишається невідомим', 'What remains unknown')}</h4><p>${t('Глибину відповідного досвіду, професійний стаж, можливість працювати в потрібному регіоні, доступність та інтерес до ролі. Публічний пошук змін у коді цього не встановлює.', 'Depth of relevant experience, professional tenure, regional work eligibility, availability and interest. Public code-change discovery does not establish these.')}</p></div></article>`).join('')}</div>` : `<p class="blocked-note">${t('Цей прохід не дав акаунтів для подальшого дослідження. Перегляньте стани джерел; порожній результат не доводить відсутність людей на ринку.', 'This run yielded no accounts for further research. Inspect the lane statuses; an empty run does not establish market scarcity.')}</p>`}
      <p class="research-footnote">${t('Однакові GitHub ID об’єднуються. Збіг імен не використовується для зіставлення осіб. Системи компанії, приватні контакти й повідомлення не залучені.', 'Records sharing a GitHub ID are grouped. Names are not used to resolve identity. Company systems, private contact details and messaging are not involved.')}</p>` : ''}
    ${!staticView && !report ? renderPilotFeedback(pilotFeedback, lang, false) : ''}
  </section>`;
}

export function researchDocument(report, lang = 'uk', imported = true, showcase = false) {
  const content = renderResearch(report, lang, { staticView: true, imported, showcase });
  const language = lang === 'en' ? 'en' : 'uk';
  return `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Signal Desk — ${language === 'uk' ? 'Пошуковий прохід' : 'Research brief'}</title><style>body{margin:0;padding:24px;background:#f4f3ed;color:#1b3029;font:15px/1.6 system-ui,sans-serif}main{max-width:1050px;margin:auto}h2{font-size:32px;line-height:1.2}a{color:#255c43}p{margin:10px 0}.eyebrow{font-size:12px;letter-spacing:1px}.research-summary,.research-lanes{display:flex;gap:16px;flex-wrap:wrap;margin:24px 0}.research-summary>div,.research-lanes>article{flex:1;min-width:220px;padding:18px;border:1px solid #d6dcd1;border-radius:10px;background:#fffefa}.research-summary strong{display:block;font-size:26px}.research-summary span{font-size:12px}.research-footnote,.research-boundary{font-size:13px;color:#58675f}.research-lead{padding:24px;margin:20px 0;border:1px solid #d6dcd1;border-radius:12px;background:#fffefa;overflow-wrap:anywhere}.research-lead header{display:flex;flex-wrap:wrap;justify-content:space-between;gap:12px}.research-lead h3{margin:0}.research-lead header span{color:#79541c}.research-lead li{margin:18px 0}.research-lead small{color:#58675f}.research-next{background:#e9efe5;padding:16px;border-radius:8px}.research-next h4{margin:0}.blocked-note{padding:18px;background:#f5eddb}summary{cursor:pointer}@media(max-width:600px){body{padding:12px}.research-lead{padding:18px}h2{font-size:26px}}@media print{.research-lead{break-inside:avoid}}</style></head><body><main>${content}</main></body></html>`;
}
