// Presentation of the engine's active search plan and derived evidence counts.
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderSearchPlan(view, lang) {
  const t=(uk,en)=>lang==='uk'?uk:en, l=x=>x?.[lang]||x?.uk||'', e=escapeHTML;
  const plan=view.plan;
  return `<details class="search-plan" id="search-plan"><summary><span class="plan-summary-main"><span class="plan-number">01</span><span><strong>${t('Запит керує пошуком','The brief drives the research')}</strong><small>${e(l(plan.objective))}</small></span></span><span class="plan-summary-end">${plan.requiredCriterionIds.length} ${t('критерії','criteria')} · ${plan.activeHypothesisIds.length} ${t('напрямки','channels')} <span class="edit-label">${t('Змінити ↓','Edit ↓')}</span></span></summary>
  <form id="plan-form"><div class="plan-intro"><p>${t('Сформулюйте результат, виберіть обов’язкові критерії й напрямки. Це змінює, які знахідки доступні та які докази потрібні для передачі.','Define the outcome, select required criteria and research channels. This changes which findings are available and which evidence the handoff requires.')}</p><p>${t('Текст запиту пояснює задум. Правила задаються перемикачами нижче; ШІ не тлумачить цей текст автоматично.','The objective explains the intent. The controls below define the rules; AI does not automatically interpret this text.')}</p></div>
  <label class="plan-objective" for="plan-objective">${t('Яку задачу має вирішити ця людина?','What problem should this person solve?')}<textarea id="plan-objective" name="objective" rows="2" maxlength="2000" required>${e(l(plan.objective))}</textarea></label>
  <div class="plan-fields"><fieldset><legend>${t('Обов’язкові докази','Required evidence')}</legend><p>${t('Оберіть щонайменше один. Інші твердження залишаться додатковим контекстом.','Select at least one. Other claims remain supplementary context.')}</p>${view.project.criteria.map(c=>`<label class="plan-option"><input type="checkbox" name="criterion" value="${e(c.id)}" ${plan.requiredCriterionIds.includes(c.id)?'checked':''}><span><strong>${e(l(c.label))}</strong><small>${t('Потрібен прийнятий актуальний доказ','Needs accepted current evidence')}</small></span></label>`).join('')}</fieldset>
  <fieldset><legend>${t('Знахідки яких напрямів враховуємо','Which channels’ findings to include')}</legend><p>${t('Вимкнення виключає вже зібрані знахідки напряму з поточного огляду й передачі. Живого пошуку тут немає.','Turning a channel off excludes its already-collected findings from this review and handoff. No live search runs here.')}</p>${view.project.hypotheses.map(h=>`<label class="plan-option"><input type="checkbox" name="hypothesis" value="${e(h.id)}" ${plan.activeHypothesisIds.includes(h.id)?'checked':''}><span><strong>${e(l(h.label))}</strong><small>${e(l(h.rationale))}</small></span></label>`).join('')}</fieldset></div>
  <div class="plan-bottom"><label for="plan-reason">${t('Чому змінюємо план?','Why change the plan?')}<input id="plan-reason" name="reason" required maxlength="500" placeholder="${t('Наприклад: хочемо перевірити внесок одного каналу','For example: test the contribution of one channel')}"></label><button type="submit" class="button primary" id="apply-plan">${t('Застосувати новий план','Apply the new plan')} →</button></div><p class="plan-warning">${t('Зміна запиту, критеріїв або напрямків скасовує попередні перевірки та схвалення. Відомий конфлікт особи залишається видимим навіть після вимкнення каналу.','Changing the objective, criteria or channels invalidates prior reviews and approvals. A known identity conflict remains visible even after a channel is disabled.')}</p></form></details>`;
}
export function renderHypothesisResults(view, lang) {
 const t=(uk,en)=>lang==='uk'?uk:en,l=x=>x?.[lang]||x?.uk||'',e=escapeHTML;
 return `<div class="hypothesis-results">${view.hypotheses.map(h=>`<article data-hypothesis="${e(h.id)}" class="hypothesis-result ${h.active?'':'inactive'}"><div class="hypothesis-result-title"><strong>${e(l(h.label))}</strong><span class="badge ${h.active?'good':''}">${h.active?t('У плані','In plan'):t('Виключено','Excluded')}</span></div><p>${e(l(h.rationale))}</p><div class="channel-numbers"><span><b>${h.acceptedEvidence}</b>${t('прийнято','accepted')}</span><span><b>${h.rejectedEvidence}</b>${t('відхилено','rejected')}</span><span><b>${h.pendingEvidence}</b>${t('очікує','pending')}</span><span><b>${h.staleEvidence}</b>${t('старі','stale')}</span></div><div class="channel-outcome">${t('Внесок у схвалені передачі:','Contribution to approved handoffs:')} <strong>${h.contributingApproved}</strong></div></article>`).join('')}</div><p class="hint">${t('Лічильники стосуються тверджень, а не найнятих людей. Внесок зараховується лише за прийнятий актуальний доказ обов’язкового критерію. Одна передача може мати внесок кількох каналів; ці числа не додаються як окремі успіхи.','Counts refer to claims, not hires. Contribution requires accepted current evidence for a required criterion. One handoff may have contributions from multiple channels; these counts are not additive wins.')}</p>`;
}
export function renderCoverage(view,lang) {
 const t=(uk,en)=>lang==='uk'?uk:en,l=x=>x?.[lang]||x?.uk||'',e=escapeHTML;
 return `<section class="coverage-panel"><div class="panel-heading"><h3>${t('Де бракує доказів','Where evidence is missing')}</h3><small>${view.metrics.people} ${t('карток у плані','profiles in plan')}</small></div><div class="coverage-table" role="table" aria-label="${t('Покриття критеріїв доказами','Criterion evidence coverage')}"><div class="coverage-row head" role="row"><span role="columnheader">${t('Обов’язковий критерій','Required criterion')}</span><span role="columnheader">${t('Є свіже джерело','Fresh source')}</span><span role="columnheader">${t('Доказ прийнято','Evidence accepted')}</span><span role="columnheader">${t('Бракує доказу','Evidence gap')}</span></div>${view.coverage.map(row=>`<div class="coverage-row" data-criterion="${e(row.criterionId)}" role="row"><span role="cell">${e(l(view.project.criteria.find(c=>c.id===row.criterionId).label))}</span><strong role="cell">${row.proposedPeople}</strong><strong role="cell" class="accepted-count">${row.reviewedPeople}</strong><strong role="cell">${row.missingPeople}</strong></div>`).join('')}</div><p class="hint">${t('Рахуємо унікальні картки для кожного критерію. Кілька джерел однієї людини не збільшують її вагу. «Є свіже джерело» ще не означає, що його зміст прийнято; конфлікт особи додатково блокує передачу.','Unique profiles are counted per criterion. Multiple sources for one person do not increase that count. Having a fresh source does not mean its content was accepted; identity conflicts independently block handoff.')}</p></section>`;
}
